/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotao;

import java.awt.AWTKeyStroke;
import java.awt.Component;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Set;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;

/**
 *
 * @author HeitorScalco
 */
public class Tela_login extends javax.swing.JFrame {

    /**
     * Creates new form Tela_login
     */
    public Tela_login() {
        initComponents();
        this.setLocationRelativeTo(null);

        JB_Login.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "login");
        JB_Login.getActionMap().put("login", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {

                logar();

            }
        });

        JB_Sair.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "Sair");
        JB_Sair.getActionMap().put("Sair", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {

                System.exit(0);

            }
        });
        
        considerarEnterComoTab(JTF_Login);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JB_Login = new javax.swing.JButton();
        JB_Sair = new javax.swing.JButton();
        JTF_Login = new javax.swing.JTextField();
        JTF_Senha = new javax.swing.JPasswordField();
        JL_Gerenciador_Tickets = new javax.swing.JLabel();
        JL_Login = new javax.swing.JLabel();
        JL_Senha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        JB_Login.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotao/logon.png"))); // NOI18N
        JB_Login.setToolTipText("Pressione ENTER para LOGAR");
        JB_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_LoginActionPerformed(evt);
            }
        });

        JB_Sair.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JB_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotao/delete.png"))); // NOI18N
        JB_Sair.setToolTipText("Pressione ESC para Sair");
        JB_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SairActionPerformed(evt);
            }
        });

        JTF_Login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        JTF_Senha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        JL_Gerenciador_Tickets.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        JL_Gerenciador_Tickets.setText("Sistema Gerenciador de Tickets");

        JL_Login.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JL_Login.setText("Login:");

        JL_Senha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JL_Senha.setText("Senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_Login)
                    .addComponent(JL_Senha))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JTF_Login)
                        .addComponent(JTF_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JB_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(JB_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(JL_Gerenciador_Tickets)
                .addGap(39, 39, 39))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_Gerenciador_Tickets)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_Login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_Senha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_LoginActionPerformed

        logar();

    }//GEN-LAST:event_JB_LoginActionPerformed

    private void JB_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SairActionPerformed

        System.exit(0); //fecha o programa todo

    }//GEN-LAST:event_JB_SairActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
    }//GEN-LAST:event_formFocusLost

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus

        JTF_Login.setText("");
        JTF_Senha.setText("");

    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        JTF_Login.requestFocus();

    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Login;
    private javax.swing.JButton JB_Sair;
    private javax.swing.JLabel JL_Gerenciador_Tickets;
    private javax.swing.JLabel JL_Login;
    private javax.swing.JLabel JL_Senha;
    private javax.swing.JTextField JTF_Login;
    private javax.swing.JPasswordField JTF_Senha;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void logar() {

        try {
            aberto = e.situacaoEvento();
            String login = JTF_Login.getText();
            String senha = JTF_Senha.getText();

            //Conexão com o banco
//            Class.forName("com.mysql.jdbc.Driver");
//            Statement st = con.createStatement();
            if (login.equals("") || senha.equals("")) {
                JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos, por favor tente novamente!", "Erro", JOptionPane.ERROR_MESSAGE);

            } else {
                Usuario u = new Usuario(login, senha);
//                ResultSet rs = st.executeQuery("SELECT * FROM b_usuarios WHERE login like '" + login + "' AND senha like '" + senha + "'");
//                boolean login_correto = false;
//                Integer tipo_usuario = null;

                if (u.isLogin_correto()) {

                    if (u.isLogado() && !login.equals("root")) {

                        JOptionPane.showMessageDialog(null, "O usuário já está logado em outro computador!", "Atenção", JOptionPane.ERROR_MESSAGE);

                    } else {

                        if (u.getTipo_usuario() == 2) {

                            new TelaAdministrador().setVisible(true);
                            u.usuario = login;
                            u.setLogado(true);
                            dispose();

                        } else if (u.getTipo_usuario() == 1 && aberto) {

                            new TelaVenderProduto().setVisible(true);
                            u.usuario = login;
                            u.setLogado(true);

                        } else if (u.getTipo_usuario() == 0) {

                            new Tela_valida_ticket().setVisible(true);
                            u.usuario = login;
                            u.setLogado(true);

                        } else {

                            JOptionPane.showMessageDialog(null, "Não é possível acessar o caixa, pois não há evento aberto", "Não há eventos", JOptionPane.ERROR_MESSAGE);

                        }
                    }

                        u.usuario = login;

                    } else {
                    JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos, por favor tente novamente!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
                
            }
        } catch (Exception e) {

            e.toString();

        }

    }
    Evento e = new Evento();
    Boolean aberto = null;
    
    public static void considerarEnterComoTab(Component comp) {

        Set<AWTKeyStroke> keystrokes = comp.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS);
        Set<AWTKeyStroke> newKeystrokes = new HashSet<AWTKeyStroke>(keystrokes);
        newKeystrokes.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        comp.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, newKeystrokes);

    }
}
