/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotao;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;

/**
 *
 * @author guiarrd
 */
public class TelaEditarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaEditarUsuario
     */
    public TelaEditarUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        
        JB_Pesquisar.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "pesquisar");
        //Se for a letra "A", coloca uma ação de clique no botão e executa o que está no método actionPerformed
        JB_Pesquisar.getActionMap().put("pesquisar", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent a) {

                pesquisar();
                
            }
        });
        
        JB_Salvar.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_S, 0), "salvar");
        //Se for a letra "A", coloca uma ação de clique no botão e executa o que está no método actionPerformed
        JB_Salvar.getActionMap().put("salvar", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent a) {

                salvar();
                
            }
        });
        
        JB_Cancelar.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "cancelar");
        //Se for a letra "A", coloca uma ação de clique no botão e executa o que está no método actionPerformed
        JB_Cancelar.getActionMap().put("cancelar", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent a) {

                dispose();
                
            }
        });
        
        JB_ZerarLogado.setVisible(false);

        if (JCKB_AlterarSenha.isSelected() == false) {
            JPF_Senha.setEditable(false);
            JPF_ConfirmarSenha.setEditable(false);
        } else {
            JPF_Senha.setEditable(true);
            JPF_ConfirmarSenha.setEditable(true);
        }

        JCB_TipoUsuario.addItem("Gerente");
        JCB_TipoUsuario.addItem("Caixa");
        JCB_TipoUsuario.addItem("Venda");

        String[][] lista_produtos = new String[2000][];

        try {
            lista_produtos = u.getListaUsuarios();
        } catch (ProjetoException erp) {
            JOptionPane.showMessageDialog(null, "Houve um erro ao obter a lista de produtos!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        System.out.println("Passou por aqui: " + lista_produtos.length);
        for (int cont = 0; cont < lista_produtos.length; cont++) {
            JCB_Usuario.addItem(new ComboItem(lista_produtos[cont][0], lista_produtos[cont][1]));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JCB_Usuario = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        JTF_Login = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JB_Salvar = new javax.swing.JButton();
        JB_Cancelar = new javax.swing.JButton();
        JB_Pesquisar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JCB_TipoUsuario = new javax.swing.JComboBox();
        JCKB_AlterarSenha = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        JPF_Senha = new javax.swing.JPasswordField();
        JPF_ConfirmarSenha = new javax.swing.JPasswordField();
        JB_ZerarLogado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Editar Usuário");

        jLabel2.setText("Usuário:");

        jLabel3.setText("Login:");

        jLabel4.setText("Senha:");

        JB_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotao/edit.png"))); // NOI18N
        JB_Salvar.setText("Salvar");
        JB_Salvar.setToolTipText("Pressione S para SALVAR");
        JB_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SalvarActionPerformed(evt);
            }
        });

        JB_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotao/delete.png"))); // NOI18N
        JB_Cancelar.setText("Cancelar");
        JB_Cancelar.setToolTipText("Pressione ESC para CANCELAR");
        JB_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CancelarActionPerformed(evt);
            }
        });

        JB_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotao/find.png"))); // NOI18N
        JB_Pesquisar.setToolTipText("Pressione ENTER para PESQUISAR");
        JB_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_PesquisarActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo Usuário:");

        JCKB_AlterarSenha.setText("Alterar Senha?");
        JCKB_AlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCKB_AlterarSenhaActionPerformed(evt);
            }
        });

        jLabel6.setText("Confirmar Senha:");

        JB_ZerarLogado.setText("Zerar Logado");
        JB_ZerarLogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ZerarLogadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JB_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                    .addComponent(JB_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(JCB_Usuario, javax.swing.GroupLayout.Alignment.LEADING, 0, 197, Short.MAX_VALUE)
                                            .addComponent(JTF_Login, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JPF_Senha))
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JB_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JCKB_AlterarSenha))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JCB_TipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JPF_ConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JB_ZerarLogado)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(JB_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCB_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTF_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCKB_AlterarSenha)
                    .addComponent(JPF_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPF_ConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_ZerarLogado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JCB_TipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JB_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_PesquisarActionPerformed

        pesquisar();

    }//GEN-LAST:event_JB_PesquisarActionPerformed

    private void JB_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SalvarActionPerformed

        salvar();

    }//GEN-LAST:event_JB_SalvarActionPerformed

    private void JCKB_AlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCKB_AlterarSenhaActionPerformed

        if (JCKB_AlterarSenha.isSelected()) {
            JPF_Senha.setEditable(true);
            JPF_ConfirmarSenha.setEditable(true);
        } else {
            JPF_Senha.setEditable(false);
            JPF_ConfirmarSenha.setEditable(false);
        }

    }//GEN-LAST:event_JCKB_AlterarSenhaActionPerformed

    private void JB_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CancelarActionPerformed

        dispose();

    }//GEN-LAST:event_JB_CancelarActionPerformed

    private void JB_ZerarLogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ZerarLogadoActionPerformed
        
        int id_usuario_selecionado = Integer.parseInt(new Usuario().getUsuario("" + JCB_Usuario.getSelectedItem())[0][0]);
        Usuario usuario_logado = new Usuario(id_usuario_selecionado);
        System.out.println("login do cara: " + usuario_logado.login + " usuario do cara: " + usuario_logado.usuario);
        usuario_logado.zerarLogado(false);
        
    }//GEN-LAST:event_JB_ZerarLogadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Cancelar;
    private javax.swing.JButton JB_Pesquisar;
    private javax.swing.JButton JB_Salvar;
    private javax.swing.JButton JB_ZerarLogado;
    private javax.swing.JComboBox JCB_TipoUsuario;
    private javax.swing.JComboBox JCB_Usuario;
    private javax.swing.JCheckBox JCKB_AlterarSenha;
    private javax.swing.JPasswordField JPF_ConfirmarSenha;
    private javax.swing.JPasswordField JPF_Senha;
    private javax.swing.JTextField JTF_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    Usuario u = new Usuario(1);
    String login = "";

    private void salvar() {

        if (JPF_Senha.isEditable() && JPF_Senha.getPassword().equals("")) {

            JOptionPane.showMessageDialog(null, "A senha não pode estar em branco!", "senha requerida", JOptionPane.ERROR_MESSAGE);

        } else if (JPF_Senha.isEditable() && !JPF_Senha.getPassword().equals("")) {

            if (u.existe(JTF_Login.getText()) && !JTF_Login.getText().equals(login)) {

                JOptionPane.showMessageDialog(null, "Já existe um usuário com este login! Por favor, tente outro", "Login existente", JOptionPane.ERROR_MESSAGE);
                System.out.println("JCB_Usuario.getSelectedItem(): " + JCB_Usuario.getSelectedItem());

            } else {

                u.setLogin(JTF_Login.getText());
                if (JPF_Senha.getText().equals(JPF_ConfirmarSenha.getText())) {

                    u.setSenha(JPF_Senha.getText());
                    String tipo_usuario = (String) JCB_TipoUsuario.getSelectedItem();
                    if (tipo_usuario.equals("Gerente")) {
                        u.setTipo_usuario(2);
                    } else if (tipo_usuario.equals("Caixa")) {
                        u.setTipo_usuario(1);
                    } else if (tipo_usuario.equals("Venda")) {
                        u.setTipo_usuario(0);
                    }

                    u.atualizaInformacoesDB();
                    JOptionPane.showMessageDialog(null, "Usuário alterado com sucesso!");

                } else {

                    JOptionPane.showMessageDialog(null, "As senhas não conferem!", "Senhas incorretas", JOptionPane.ERROR_MESSAGE);

                }

            }

        } else if (!JPF_Senha.isEditable()) {

            if (u.existe(JTF_Login.getText()) && !JTF_Login.getText().equals(login)) {

                JOptionPane.showMessageDialog(null, "Já existe um usuário com este login! Por favor, tente outro", "Login existente", JOptionPane.ERROR_MESSAGE);
                System.out.println("JCB_Usuario.getSelectedItem(): " + JCB_Usuario.getSelectedItem());

            } else {

                u.setLogin(JTF_Login.getText());
                String tipo_usuario = (String) JCB_TipoUsuario.getSelectedItem();
                if (tipo_usuario.equals("Gerente")) {
                    u.setTipo_usuario(2);
                } else if (tipo_usuario.equals("Caixa")) {
                    u.setTipo_usuario(1);
                } else if (tipo_usuario.equals("Venda")) {
                    u.setTipo_usuario(0);
                }

                u.atualizaInformacoesDB();
                JOptionPane.showMessageDialog(null, "Usuário alterado com sucesso!");
            }
        }
    }
    
    public void pesquisar(){
        
        ComboItem item_selecionado;
        item_selecionado = (ComboItem) JCB_Usuario.getSelectedItem();

        u = new Usuario(Integer.parseInt(item_selecionado.codigo));

        JTF_Login.setText(u.getLogin());
        login = u.getLogin();
        JB_ZerarLogado.setVisible(true);
        
    }

}
