/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projetotao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HeitorScalco
 */
public class TelaFecharEvento extends javax.swing.JFrame {

    /**
     * Creates new form Tela1
     */
    public TelaFecharEvento() {
        initComponents();
        setLocationRelativeTo(null);
        eventosDisponiveis();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT_Eventos = new javax.swing.JTable();
        JB_Fechar = new javax.swing.JButton();
        JT_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Fechar Evento");

        JT_Eventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Data Início", "Data Fim"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JT_Eventos);

        JB_Fechar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JB_Fechar.setText(" Fechar Evento");
        JB_Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_FecharActionPerformed(evt);
            }
        });

        JT_Cancelar.setText("Cancelar");
        JT_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JB_Fechar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JT_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JT_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(JB_Fechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_FecharActionPerformed

        fecharEvento();

    }//GEN-LAST:event_JB_FecharActionPerformed

    private void JT_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_CancelarActionPerformed

        dispose();

    }//GEN-LAST:event_JT_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFecharEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFecharEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFecharEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFecharEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFecharEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Fechar;
    private javax.swing.JButton JT_Cancelar;
    private javax.swing.JTable JT_Eventos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

private DefaultTableModel dtm;
    private Connection con;
    private Statement st;
    private ResultSet rs;

    private void eventosDisponiveis() {

        dtm = (DefaultTableModel) JT_Eventos.getModel();
        try {

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(new CoreSql().db_conexao);
            st = con.createStatement();

        } catch (Exception e) {

            System.out.println("Erro: " + e.toString());

        }
        //executar sql
        try {

            rs = st.executeQuery("SELECT * FROM b_eventos WHERE aberto = 1");
            limpaTabela();
            while (rs.next()) {

                //cria linha
                dtm.addRow(new Object[]{rs.getString("Id"), rs.getString("data_inicio"), rs.getString("data_fim")});

            }

            st.close();
            con.close();

        } catch (Exception e) {

            System.out.println("Erro: " + e.toString());

        }
    }

    public void limpaTabela() {
        //Se a tabela está preenchida ela limpa
        if (dtm.getRowCount() != 0) { //se tiver linhas na tabela
            //Limpa tabela
            JT_Eventos.selectAll();//seleciona todas
            int[] l = JT_Eventos.getSelectedRows();
            for (int i = (l.length - 1); i >= 0; i--) {
                dtm.removeRow(l[i]); //remove tudo uma por vez ate o for terminar
            }
        }
    }

    private void fecharEvento(){
        
        int row = JT_Eventos.getSelectedRow();
        int codigo = Integer.parseInt((String)JT_Eventos.getValueAt(row, 0));
        CoreSql c = new CoreSql();
        String sql = "UPDATE b_eventos SET aberto = 0 WHERE Id = " + codigo;
        c.executarQuery(sql, false, null);
        
    }
    
//    private void fecharVendas(){
//        
//        CoreSql c = new CoreSql();
//        String Sql = "UPDATE b_ticket SET ";
//        
//        
//    }
    

}
