/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotao;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;

/**
 *
 * @author guiarrd
 */
public class TelaAdicionarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdicionarUsuario
     */
    public TelaAdicionarUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        JB_Criar.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "criar");
        JB_Criar.getActionMap().put("criar", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {

                novoUsuario();

            }
        });

        JB_Cancelar.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "cancelar");
        JB_Cancelar.getActionMap().put("cancelar", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {

                dispose();

            }
        });

        JRB_Gerente.setSelected(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        JTF_Login = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JRB_Gerente = new javax.swing.JRadioButton();
        JRB_Caixa = new javax.swing.JRadioButton();
        JB_Criar = new javax.swing.JButton();
        JB_Cancelar = new javax.swing.JButton();
        JTF_Senha = new javax.swing.JPasswordField();
        JRB_Venda = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Login:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Novo Usuário");

        jLabel3.setText("Senha:");

        buttonGroup2.add(JRB_Gerente);
        JRB_Gerente.setText("Gerente");

        buttonGroup2.add(JRB_Caixa);
        JRB_Caixa.setText("Caixa");

        JB_Criar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JB_Criar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotao/add.png"))); // NOI18N
        JB_Criar.setToolTipText("Pressione ENTER para CRIAR");
        JB_Criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CriarActionPerformed(evt);
            }
        });

        JB_Cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JB_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotao/delete.png"))); // NOI18N
        JB_Cancelar.setToolTipText("Pressione ESC para CANCELAR");
        JB_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CancelarActionPerformed(evt);
            }
        });

        buttonGroup2.add(JRB_Venda);
        JRB_Venda.setText("Bar");
        JRB_Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_VendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JB_Criar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(JTF_Login)
                            .addComponent(JTF_Senha, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JRB_Gerente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(JRB_Caixa)
                        .addGap(27, 27, 27)
                        .addComponent(JRB_Venda)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTF_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTF_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRB_Gerente)
                    .addComponent(JRB_Caixa)
                    .addComponent(JRB_Venda))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Criar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_CriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CriarActionPerformed

        novoUsuario();

    }//GEN-LAST:event_JB_CriarActionPerformed

    private void JB_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CancelarActionPerformed

        dispose();

    }//GEN-LAST:event_JB_CancelarActionPerformed

    private void JRB_VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_VendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB_VendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Cancelar;
    private javax.swing.JButton JB_Criar;
    private javax.swing.JRadioButton JRB_Caixa;
    private javax.swing.JRadioButton JRB_Gerente;
    private javax.swing.JRadioButton JRB_Venda;
    private javax.swing.JTextField JTF_Login;
    private javax.swing.JPasswordField JTF_Senha;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    CoreSql c = new CoreSql();
    String login = "", senha = "";

    private void novoUsuario() {

        login = JTF_Login.getText();
        senha = JTF_Senha.getText();

        if (login.equals("")) {

            JOptionPane.showMessageDialog(null, "O login não pode ficar em branco!", "Erro", JOptionPane.ERROR_MESSAGE);

        } else if (senha.equals("")) {

            JOptionPane.showMessageDialog(null, "A senha não pode ficar em branco!", "Erro", JOptionPane.ERROR_MESSAGE);

        } else {

//            verificaLoginUsuario();
            u = new Usuario(login, senha);
            
            if (JRB_Gerente.isSelected()) {

                u.setTipo_usuario(2);

            } else if (JRB_Caixa.isSelected()) {

                u.setTipo_usuario(1);
                
            } else {

                u.setTipo_usuario(0);

            }

            if(u.existe(login)){
                
                JOptionPane.showMessageDialog(null, "Já existe um usuário com este login. Por favor, tente outro!", "Usuário existente", JOptionPane.ERROR_MESSAGE);
                
            } else {
                
                u.addUsuario();
                JOptionPane.showMessageDialog(null, "Usuário adicionado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                
            }
            
        }
    }
//    private void verificaLoginUsuario() {
//
//        String login_sql = "SELECT id FROM b_usuarios WHERE login like '" + login + "';";
//        String retorno[][] = c.executarQuery(login_sql, true, new String[]{"id"});
//        if (retorno != null) {
//
//            JOptionPane.showMessageDialog(null, "Já existe um usuário com este login!", "Usuário existente", JOptionPane.ERROR_MESSAGE);
//
//        }
//
//    }

    Usuario u;

}
