/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and ope template in the editor.
 */
package projetotao;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;

/**
 *
 * @author HeitorScalco
 */
public class Tela_valida_ticket extends javax.swing.JFrame {

    /**
     * Creates new form Tela_valida_ticket
     */
    public Tela_valida_ticket() {
        initComponents();
        setLocationRelativeTo(null);

        this.setExtendedState(MAXIMIZED_BOTH);

        JB_Validar.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "validar");
        JB_Validar.getActionMap().put("validar", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                aberto = e.situacaoEvento();
                if (aberto) {

                    try {
                        if (validar()) {
                            jPanel2.setBackground(Color.green);
                            //JOptionPane.showMessageDialog(null, "O Ticket foi contabilizado!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                            JTF_Cod_Barras.setText("");
                            JTF_Cod_Barras.requestFocus();

                        } else {
                            jPanel2.setBackground(Color.red);
                            JTF_Cod_Barras.setText("");
                            JTF_Cod_Barras.requestFocus();
                            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao validar o ticket", "Atenção", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (ProjetoException ert) {
                        jPanel2.setBackground(Color.red);
                        //JOptionPane.showMessageDialog(null, ert.getMessage(), "Atenção", JOptionPane.ERROR_MESSAGE);
                        JTF_Cod_Barras.setText("");
                        JTF_Cod_Barras.requestFocus();

                    }

                } else {
                    jPanel2.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "Não existe um evento aberto para validar o ticket!", "Erro", JOptionPane.ERROR_MESSAGE);
                    JTF_Cod_Barras.setText("");
                    JTF_Cod_Barras.requestFocus();

                }

            }
        });

        JB_Cancelar.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "cancelar");
        JB_Cancelar.getActionMap().put("cancelar", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {

                dispose();

            }
        });

        u.getUsuarioLogado();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JB_Validar = new javax.swing.JButton();
        JL_Valida_Ticket = new javax.swing.JLabel();
        JTF_Cod_Barras = new javax.swing.JTextField();
        JL_Leitor_Cod_Barras = new javax.swing.JLabel();
        JB_Cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        JB_Validar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JB_Validar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotao/check.png"))); // NOI18N
        JB_Validar.setText("Contabilizar");
        JB_Validar.setToolTipText("Pressione ENTER para CONTABILIZAR");
        JB_Validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ValidarActionPerformed(evt);
            }
        });

        JL_Valida_Ticket.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JL_Valida_Ticket.setText("Contabilizar Ticket");

        JTF_Cod_Barras.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JTF_Cod_Barras.setToolTipText("");
        JTF_Cod_Barras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTF_Cod_BarrasFocusGained(evt);
            }
        });

        JL_Leitor_Cod_Barras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_Leitor_Cod_Barras.setText("Passe o leitor no código de barras ou digite o código manualmente");

        JB_Cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JB_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotao/delete.png"))); // NOI18N
        JB_Cancelar.setText("Cancelar");
        JB_Cancelar.setToolTipText("Presisone ESC para CANCELAR");
        JB_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CancelarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JTF_Cod_Barras)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 42, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JB_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(JB_Validar)
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JL_Leitor_Cod_Barras)
                                .addGap(50, 50, 50))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(JL_Valida_Ticket)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(JL_Valida_Ticket)
                .addGap(18, 18, 18)
                .addComponent(JL_Leitor_Cod_Barras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTF_Cod_Barras, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_Validar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_ValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ValidarActionPerformed

        aberto = e.situacaoEvento();
        if (aberto) {

            try {
                if (validar()) {
                    jPanel2.setBackground(Color.green);
                    //JOptionPane.showMessageDialog(null, "O Ticket foi contabilizado!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    JTF_Cod_Barras.setText("");
                    JTF_Cod_Barras.requestFocus();

                } else {
                    jPanel2.setBackground(Color.red);
                    JTF_Cod_Barras.setText("");
                    JTF_Cod_Barras.requestFocus();
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro ao validar o ticket", "Atenção", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ProjetoException ert) {
                jPanel2.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, ert.getMessage(), "Atenção", JOptionPane.ERROR_MESSAGE);
                JTF_Cod_Barras.setText("");
                JTF_Cod_Barras.requestFocus();

            }

        } else {
            jPanel2.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Não existe um evento aberto para validar o ticket!", "Erro", JOptionPane.ERROR_MESSAGE);
            JTF_Cod_Barras.setText("");
            JTF_Cod_Barras.requestFocus();

        }

    }//GEN-LAST:event_JB_ValidarActionPerformed

    private void JB_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CancelarActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_JB_CancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        if (u.getTipo_usuario() == 0) {

            u.setLogado(false);

        }

    }//GEN-LAST:event_formWindowClosing

    private void JTF_Cod_BarrasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTF_Cod_BarrasFocusGained

        if (!JTF_Cod_Barras.getText().equals("")) {

            aberto = e.situacaoEvento();
            if (aberto) {

                try {
                    if (validar()) {
                        jPanel2.setBackground(Color.green);
                        //JOptionPane.showMessageDialog(null, "O Ticket foi contabilizado!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                        JTF_Cod_Barras.setText("");
                        JTF_Cod_Barras.requestFocus();

                    } else {
                        jPanel2.setBackground(Color.red);
                        JTF_Cod_Barras.setText("");
                        JTF_Cod_Barras.requestFocus();
                        JOptionPane.showMessageDialog(null, "Ocorreu um erro ao validar o ticket", "Atenção", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (ProjetoException ert) {
                    jPanel2.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, ert.getMessage(), "Atenção", JOptionPane.ERROR_MESSAGE);
                    JTF_Cod_Barras.setText("");
                    JTF_Cod_Barras.requestFocus();

                }

            } else {
                jPanel2.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Não existe um evento aberto para validar o ticket!", "Erro", JOptionPane.ERROR_MESSAGE);
                JTF_Cod_Barras.setText("");
                JTF_Cod_Barras.requestFocus();
                
            }

        }
        

    }//GEN-LAST:event_JTF_Cod_BarrasFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_valida_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_valida_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_valida_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_valida_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_valida_ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Cancelar;
    private javax.swing.JButton JB_Validar;
    private javax.swing.JLabel JL_Leitor_Cod_Barras;
    private javax.swing.JLabel JL_Valida_Ticket;
    private javax.swing.JTextField JTF_Cod_Barras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private boolean validar() throws ProjetoException {

        //try {
        //pega o conteudo de um elemento da tela
        int codigo = Integer.parseInt(JTF_Cod_Barras.getText());
        Ticket t = new Ticket();
            //t.setTicket(codigo);

        //t.getTicket();
        if (t.contabilizar(codigo)) {
            //JOptionPane.showMessageDialog(null, "O Ticket foi contabilizado!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            return true;
        }
        return false;
        //} catch (ProjetoException excessao) {
        //JOptionPane.showMessageDialog(null, excessao.getMessage(), "Atenção", JOptionPane.ERROR_MESSAGE);
        //return false;
        //}

    }
    Evento e = new Evento();
    Usuario u = new Usuario();
    Boolean aberto = null;
}
