/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotao;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HeitorScalco
 */
public class TelaEditarProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdicaoProdutos
     */
    public TelaEditarProduto() {
        initComponents();
        setLocationRelativeTo(null);

        JB_Consultar.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "consultar");
        JB_Consultar.getActionMap().put("consultar", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {

                int item_selecionado = JCB_Produto.getSelectedIndex();
                System.out.print("Item selecionado: " + item_selecionado);
                JTF_Desc_Produto.setText(prod.descricao);
                JTF_Valor_Produto.setText("" + prod.valor_venda);

            }
        });
        
        JB_Salvar.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_S, 0), "salvar");
        JB_Salvar.getActionMap().put("salvar", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {

            
            
            }
        });

        JCB_Hab_Venda.addItem("Sim");
        JCB_Hab_Venda.addItem("Não");
        
        //TelaEditarProduto tela = new TelaEditarProduto();

        Produto p = new Produto(1);

        //jComboBox1.
        String[][] lista_produtos = new String[2000][];

        try {
            lista_produtos = p.getListaProdutos();
        } catch (ProjetoException erp) {
            JOptionPane.showMessageDialog(null, "Houve um erro ao obter a lista de produtos!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        System.out.println("Passou por aqui: " + lista_produtos.length);
        for (int cont = 0; cont < lista_produtos.length; cont++) {
            JCB_Produto.addItem(new ComboItem(lista_produtos[cont][0], lista_produtos[cont][1]));
            System.out.println("Produto: " + lista_produtos[cont][0]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        JCB_Produto = new javax.swing.JComboBox();
        JTF_Desc_Produto = new javax.swing.JTextField();
        JCB_Hab_Venda = new javax.swing.JComboBox();
        JTF_Valor_Produto = new javax.swing.JTextField();
        JL_Desc_Produto = new javax.swing.JLabel();
        JB_Consultar = new javax.swing.JButton();
        JL_Editar_Produtos = new javax.swing.JLabel();
        JL_Produto = new javax.swing.JLabel();
        JL_Valor_Produto = new javax.swing.JLabel();
        JL_Habilitar_Venda = new javax.swing.JLabel();
        JB_Salvar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        JCB_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_ProdutoActionPerformed(evt);
            }
        });

        JTF_Desc_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_Desc_ProdutoActionPerformed(evt);
            }
        });

        JCB_Hab_Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_Hab_VendaActionPerformed(evt);
            }
        });

        JTF_Valor_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_Valor_ProdutoActionPerformed(evt);
            }
        });

        JL_Desc_Produto.setText("Descrição do Produto:");

        JB_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotao/find.png"))); // NOI18N
        JB_Consultar.setToolTipText("Pressione ENTER para PESQUISAR");
        JB_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ConsultarActionPerformed(evt);
            }
        });

        JL_Editar_Produtos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JL_Editar_Produtos.setText("Editar Produtos");

        JL_Produto.setText("Produto: ");

        JL_Valor_Produto.setText("Preço de Venda:");

        JL_Habilitar_Venda.setText("Habilitado para venda? (Por padrão)");

        JB_Salvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JB_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotao/edit.png"))); // NOI18N
        JB_Salvar.setText("Salvar");
        JB_Salvar.setToolTipText("Pressione S para SALVAR");
        JB_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SalvarActionPerformed(evt);
            }
        });

        jLabel1.setText("Preço de Custo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(JL_Editar_Produtos)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_Desc_Produto)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JTF_Desc_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCB_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JB_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JL_Habilitar_Venda)
                            .addComponent(JCB_Hab_Venda, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JB_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTF_Valor_Produto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JL_Valor_Produto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_Produto, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_Editar_Produtos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JL_Produto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JCB_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_Consultar))
                .addGap(18, 18, 18)
                .addComponent(JL_Desc_Produto)
                .addGap(2, 2, 2)
                .addComponent(JTF_Desc_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JL_Valor_Produto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTF_Valor_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(JL_Habilitar_Venda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JCB_Hab_Venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(JB_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ConsultarActionPerformed
        ComboItem item_selecionado;
        item_selecionado = (ComboItem) JCB_Produto.getSelectedItem();
        System.out.print("Item selecionado: " + item_selecionado.codigo);
        
        prod = new Produto(Integer.parseInt(item_selecionado.codigo));

        JTF_Desc_Produto.setText(prod.descricao);
        JTF_Valor_Produto.setText("" + prod.valor_venda);        
        jTextField1.setText("" + prod.valor_compra);


    }//GEN-LAST:event_JB_ConsultarActionPerformed

    private void JCB_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_ProdutoActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_JCB_ProdutoActionPerformed

    private void JTF_Desc_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_Desc_ProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_Desc_ProdutoActionPerformed

    private void JCB_Hab_VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_Hab_VendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCB_Hab_VendaActionPerformed

    private void JTF_Valor_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_Valor_ProdutoActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_JTF_Valor_ProdutoActionPerformed

    private void JB_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SalvarActionPerformed

        salvar(); 

    }//GEN-LAST:event_JB_SalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                TelaEditarProduto tela = new TelaEditarProduto();;
//
//                Produto p = new Produto(1);
//
//                //jComboBox1.
//                String[][] lista_produtos = new String[2000][];
//
//                try {
//                    lista_produtos = p.getListaProdutos();
//                } catch (ProjetoException erp) {
//                    JOptionPane.showMessageDialog(null, "Houve um erro ao obter a lista de produtos!", "Erro", JOptionPane.ERROR_MESSAGE);
//                }
//                System.out.println("Passou por aqui: " + lista_produtos.length);
//                for (int cont = 0; cont < lista_produtos.length; cont++) {
//                    tela.JCB_Produto.addItem(lista_produtos[cont][1]);
//                    System.out.println("Produto: " + lista_produtos[cont][1]);
//                }

                tela.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Consultar;
    private javax.swing.JButton JB_Salvar;
    private javax.swing.JComboBox JCB_Hab_Venda;
    private javax.swing.JComboBox JCB_Produto;
    private javax.swing.JLabel JL_Desc_Produto;
    private javax.swing.JLabel JL_Editar_Produtos;
    private javax.swing.JLabel JL_Habilitar_Venda;
    private javax.swing.JLabel JL_Produto;
    private javax.swing.JLabel JL_Valor_Produto;
    private javax.swing.JTextField JTF_Desc_Produto;
    private javax.swing.JTextField JTF_Valor_Produto;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
Produto prod = new Produto(1);

    private void salvar(){
        
        prod.descricao = JTF_Desc_Produto.getText();
        prod.valor_venda = Double.parseDouble(JTF_Valor_Produto.getText());
        prod.valor_compra = Double.parseDouble(jTextField1.getText());
        String item = (String) JCB_Hab_Venda.getSelectedItem();
        if (item.equals("Sim")) {

            prod.liberar_venda = true;

        } else {

            prod.liberar_venda = false;

        }
        prod.atualizaInformacoesDB(); //atualiza a tabela do banco
        
    }

}
